# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_over.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 281)
        Dialog.setFixedSize(Dialog.size())
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 10, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.name_line = QtWidgets.QLineEdit(Dialog)
        self.name_line.setGeometry(QtCore.QRect(10, 100, 121, 21))
        self.name_line.setObjectName("name_line")
        self.lines_label = QtWidgets.QLabel(Dialog)
        self.lines_label.setGeometry(QtCore.QRect(170, 90, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lines_label.setFont(font)
        self.lines_label.setObjectName("lines_label")
        self.lvl_label = QtWidgets.QLabel(Dialog)
        self.lvl_label.setGeometry(QtCore.QRect(170, 130, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lvl_label.setFont(font)
        self.lvl_label.setObjectName("lvl_label")
        self.quit_button = QtWidgets.QPushButton(Dialog)
        self.quit_button.setGeometry(QtCore.QRect(120, 240, 101, 31))
        self.quit_button.setObjectName("quit_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Game Over"))
        self.label_2.setText(_translate("Dialog", "Name"))
        self.lines_label.setText(_translate("Dialog", "Lines:"))
        self.lvl_label.setText(_translate("Dialog", "Level:"))
        self.name_line.setText(_translate("Dialog", "Player"))
        self.quit_button.setText(_translate("Dialog", "Quit"))
