# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(246, 416)
        MainWindow.setFixedSize(MainWindow.size())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(50, 260, 151, 41))
        self.start_button.setObjectName("start_button")
        self.settings_button = QtWidgets.QPushButton(self.centralwidget)
        self.settings_button.setGeometry(QtCore.QRect(10, 310, 81, 31))
        self.settings_button.setObjectName("settings_button")
        self.score_button = QtWidgets.QPushButton(self.centralwidget)
        self.score_button.setGeometry(QtCore.QRect(150, 310, 81, 31))
        self.score_button.setObjectName("score_button")
        self.logo_pic = QtWidgets.QLabel(self.centralwidget)
        self.logo_pic.setGeometry(QtCore.QRect(10, 10, 220, 221))
        self.logo_pic.setMinimumSize(QtCore.QSize(220, 221))
        self.logo_pic.setText("")
        self.logo_pic.setObjectName("logo_pic")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(90, 350, 75, 23))
        self.exit_button.setObjectName("exit_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 246, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.settings_button.setText(_translate("MainWindow", "Settings"))
        self.score_button.setText(_translate("MainWindow", "Score"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
