# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'score_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScoreDialog(object):
    def setupUi(self, ScoreDialog):
        ScoreDialog.setObjectName("ScoreDialog")
        ScoreDialog.resize(249, 359)
        ScoreDialog.setFixedSize(ScoreDialog.size())
        self.label = QtWidgets.QLabel(ScoreDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(ScoreDialog)
        self.widget.setGeometry(QtCore.QRect(10, 65, 221, 281))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.one = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.one.setFont(font)
        self.one.setText("")
        self.one.setObjectName("one")
        self.verticalLayout.addWidget(self.one)
        self.two = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.two.setFont(font)
        self.two.setText("")
        self.two.setObjectName("two")
        self.verticalLayout.addWidget(self.two)
        self.thre = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.thre.setFont(font)
        self.thre.setText("")
        self.thre.setObjectName("thre")
        self.verticalLayout.addWidget(self.thre)
        self.four = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.four.setFont(font)
        self.four.setText("")
        self.four.setObjectName("four")
        self.verticalLayout.addWidget(self.four)
        self.five = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.five.setFont(font)
        self.five.setText("")
        self.five.setObjectName("five")
        self.verticalLayout.addWidget(self.five)

        self.retranslateUi(ScoreDialog)
        QtCore.QMetaObject.connectSlotsByName(ScoreDialog)

    def retranslateUi(self, ScoreDialog):
        _translate = QtCore.QCoreApplication.translate
        ScoreDialog.setWindowTitle(_translate("ScoreDialog", "Scores"))
        self.label.setText(_translate("ScoreDialog", "Records Table:"))
